### ISSUE TITLE
Decoding advanced serde constructions like tagged enums

### ISSUE THREAD

**Issue by monoid** [knightpp/serde_bencoded#2]
Ok, after the #1, I digged Serde sources, and one comment says that advanced features like tagged enums require "self-descriptive" formats. While bencode seems to be self-descriptive, it doesn't distinguish byte string and Unicode strings, and Serde expects Unicode strings.

There is a simple solution: the `deserialize_any` method could check if byte sequence is a valid UTF-8 string, and call either "visit_str" or "visit_bytes" depending on the result.  However, for those who do not need these advanced features, it will impose CPU penalty.  We might have two implementations (`Deserializer` and `AutoDeserializer`), or simply have a feature flag.  First possibility is more flexible, and second is easier to implement and maintain. What do you think?

The deserialize_any diff looks like:
```diff
-            b'0'..=b'9' => self.deserialize_str(visitor),
+            b'0'..=b'9' => {
+                let bytes = self.parse_byte_string()?;
+                match std::str::from_utf8(bytes) {
+                    Ok(s) => visitor.visit_borrowed_str(s),
+                    Err(_) => visitor.visit_borrowed_bytes(bytes),
+                }
+            }
```

**Comment by monoid** [comment]
OTOH, the CPU penalty will affect only those who use these advanced features.  For those who uses simple Serde, `deserialize_any` is called for neither strings nor bytes.

**Comment by knightpp** [comment]
We can make `Deserializer` struct generic and default top-level `pub fn from_bytes` will use `Deserializer<Dumb>`. Whereas the users would use `Deserializer<Auto>` if they need the feature. I think this should be possible with generics, need to try. What do you think?

**Comment by monoid** [comment]
Nice idea!  One can introduce default trait parameter to keep API fully compatible.
