### ISSUE TITLE
[request] could/should the `announce` field be optional?

### ISSUE THREAD

**Issue by alexxroche** [knightpp/serde_bencoded#5]
I used `lava_torrent::torrent::v1::TorrentBuilder` to build a torrent file and then tried to parse it with serde_bencoded.

I know the BitTorrent specification is notoriously sloppy and ambiguous, so I presumed this would have to follow the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle).

```bash
git clone https://github.com/knightpp/serde_bencoded.git
cd serde_bencoded
cargo run --example torrent -- ../../mk_torrent/sample.torrent 

    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/torrent ../../mk_torrent/sample.torrent`
Error: Message("missing field `announce`")
```

"If it's missing then just display an empty Vector?"

**Comment by knightpp** [comment]
`serde_bencoded` crate is just about bencoding. So it has nothing to do with torrent MetaInfo specification.

If you need `announce` to be optional you can change it.
[Here we have](https://github.com/knightpp/serde_bencoded/blob/e517992481b77bf005f88eeb8d8e06cb3df40a01/examples/torrent.rs#L91) `announce: String` 
And you want it to be

```rust
#[derive(Debug, Serialize, Deserialize)]
struct MetaInfo {
// ...
    announce: Option<String>,
// ...
}
```

**Comment by knightpp** [comment]
https://wiki.theory.org/BitTorrentSpecification#Metainfo_File_Structure
That website doesn't say it is optional, so I assume it is required.

**Comment by alexxroche** [comment]
I'll go and report this to lava_torrent.  Thank you for your help and patience.

**Comment by knightpp** [comment]
You are welcome :)
